baseurl: "/Rodetri"
apiname: "Test met GitHub Pages theme"
url: "http://localhost:4000"
# nav is t.b.v. generatie side-navigation menu.
# Een 'title' zonder path of url genereert slechts een kopje.
# 'path' vormt tezamen met de baseurl de url waarmee de 'href' wordt gevuld. 
# Indien een 'url' voorradig dan wordt daarmee de 'href' gevuld en dient het path slechts om te bepalen welke link active is.
# 'target: blank' zorgt er voor dat de link in een nieuw tabblad wordt geöpend.
nav:
  - title: BRK Bevragen
    subnav:
      - title: Main
        path: /
#      - title: Goals canvas
#        path: /getting-started
  - title: Specificaties v. 1.2 (Live)
    subnav:
      - title: Getting started
        path: /getting-started
      - title: User stories
        url: https://github.com/VNG-Realisatie/Haal-Centraal-BRK-bevragen/issues?q=is%3Aopen+is%3Aissue+label%3A%22user+story%22++label%3A%22BRK+bevragen+v1.2%22+
        path: /user-stories
        target: blank
      - title: Bevragen API (swagger-ui)
        path: /swagger-ui
      - title: Bevragen API (redoc)
        path: /redoc
      - title: Features
        path: /features
  - title: Specificaties v. 1.3 (IO)
    subnav:
      - title: User stories
        url: https://github.com/VNG-Realisatie/Haal-Centraal-BRK-bevragen/issues?q=is%3Aopen+is%3Aissue+label%3A%22user+story%22++label%3A%22BRK+bevragen+v1.3%22+
        path: /user-stories
        target: blank
      - title: Bevragen API (swagger-ui)
        path: /swagger-ui-io
      - title: Bevragen API (redoc)
        path: /redoc-io
      - title: Features
        path: /features
plugins:
  - jekyll-redirect-from
  - jekyll-remote-theme

remote_theme: VNG-Realisatie/jekyll-theme-haal-centraal

github: melsk-r/Rodetri

theme: jekyll-theme-time-machine

project_name: Rodetri